import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Lightbulb } from 'lucide-react';
import { useLab } from '../state/LabContext';
import { analysisQuestions, checkAnalysis, editAnalysis } from '../domain/learning';
import { ProgressBar } from '../components/ProgressBar';
import { GroupTurn } from '../components/GroupTurn';
import { GroupCheckpoint } from '../components/GroupCheckpoint';
import { OxygenBarrierDiagram } from '../components/OxygenBarrierDiagram';
export function Explanation() {
  const { state,updateSession }=useLab(); const session=state.session!;
  const index=Math.max(0,Math.min(3,session.analysisIndex ?? 0)); const question=analysisQuestions[index];
  const reviewed=!!session.analysisReviewed?.includes(question.id); const answer=session.explanationAnswers[question.id];
  const [agreed,setAgreed]=useState(false);
  useEffect(()=>setAgreed(false),[index]);
  const canCheck=answer!==undefined && (session.mode==='individual'||agreed);
  return <><ProgressBar/><section className="panel explanation-panel"><div className="eyebrow">07 / ANALISIS</div><h1>Mengapa keputusan ini berlaku?</h1><p className="muted">Gunakan bukti daripada tabung untuk menerangkan hubungan sebab dan akibat.</p><GroupTurn role="Pembentang" instruction="Ajak semua ahli memberi sebab. Ahli yang berbeza boleh membaca setiap soalan."/><div className="analysis-question-nav" aria-label="Soalan analisis">{analysisQuestions.map((q,i)=><button key={q.id} disabled={i>index&&!session.analysisReviewed?.includes(analysisQuestions[i-1].id)} aria-current={i===index?'step':undefined} className={i===index?'selected':''} onClick={()=>updateSession({...session,analysisIndex:i})}>{session.analysisReviewed?.includes(q.id)&&<CheckCircle2 size={16}/>}Soalan {i+1}</button>)}</div><div className="analysis-question"><span>SOALAN {index+1} / 4</span><h2>{question.question}</h2></div><fieldset className="hypothesis-options"><legend className="sr-only">Jawapan analisis</legend>{question.options.map((option,i)=><label key={option} className={`option-card ${answer===String(i)?'selected':''}`}><input type="radio" name={question.id} checked={answer===String(i)} onChange={()=>{setAgreed(false);updateSession(editAnalysis(session,question.id,String(i)));}}/><span className="option-letter">{String.fromCharCode(65+i)}</span><span>{option}</span></label>)}</fieldset>{!reviewed&&<GroupCheckpoint key={question.id} agreed={agreed} onAgree={setAgreed} prompt={question.id==='oxygen'?'Bincangkan sebab Tabung C tidak bercambah. Apakah hubungan air didih dan lapisan minyak dengan udara?':'Bincangkan sebab pilihan anda. Adakah semua ahli boleh menerangkannya?'}/>}<div className="analysis-check-row"><span className="small muted">Anda boleh membetulkan jawapan selepas maklum balas.</span><button className="primary" disabled={!canCheck||reviewed} onClick={()=>updateSession(checkAnalysis(session,question.id))}>Semak penjelasan</button></div>{reviewed&&<div className={`analysis-feedback ${answer===question.answer?'correct-explanation':''}`} role="status"><Lightbulb size={22}/><div><strong>{answer===question.answer?'Penjelasan anda tepat.':'Mari semak sebabnya.'}</strong><p>{question.explanation}</p>{question.id==='oxygen'&&<OxygenBarrierDiagram/>}<p className="correct-answer">Jawapan: {question.options[Number(question.answer)]}</p></div></div>}<div className="actions"><button className="secondary" disabled={index===0} onClick={()=>updateSession({...session,analysisIndex:index-1})}><ArrowLeft size={18}/>Soalan sebelumnya</button><button className="primary" disabled={!reviewed||(index===3&&!session.completedSteps.includes(6))} onClick={()=>updateSession(index<3?{...session,analysisIndex:index+1}:{...session,screen:'conclusion',step:7})}>{index<3?'Soalan seterusnya':'Bina kesimpulan'}<ArrowRight size={18}/></button></div></section></>;
}

