import { ArrowRight, UsersRound, UserRound, Clock3, FlaskConical } from 'lucide-react';
import { SeedIllustration } from '../components/SeedIllustration';
import { type Mode } from '../domain/model';
import { useLab } from '../state/LabContext';
export function Landing({ onSelect, onResume }: { onSelect: (mode: Mode) => void; onResume: () => void }) {
  const { state } = useLab();
  return <div className="landing-grid"><section className="intro"><div className="eyebrow"><span className="dot"/> BIOLOGI / EKSPERIMEN MAYA</div><h1>Satu biji benih.<br/>Tiga syarat<br/><em>untuk kehidupan.</em></h1><p className="lead">Siasat syarat percambahan biji benih.<br/>Anda yang meramal, menyediakan dan memerhati.</p><div className="experiment-tags"><span><FlaskConical size={17}/> 4 tabung didih</span><span><Clock3 size={17}/> 5 hari simulasi</span></div><div className="start-label">PILIH CARA ANDA BELAJAR</div><div className="mode-grid">{(state.settings.allowedModes === 'both' || state.settings.allowedModes === 'individual') && <button className="mode-card" onClick={() => onSelect('individual')}><UserRound size={27}/><strong>Individu</strong><span>Teroka sendiri</span><ArrowRight size={20}/></button>}{(state.settings.allowedModes === 'both' || state.settings.allowedModes === 'group') && <button className="mode-card" onClick={() => onSelect('group')}><UsersRound size={27}/><strong>Kumpulan</strong><span>2–{state.settings.maxMembers} ahli · satu tablet</span><ArrowRight size={20}/></button>}</div>{state.session && <button className="resume" onClick={onResume}>Sambung sesi: {state.session.name} <ArrowRight size={17}/></button>}</section><aside className="specimen-panel"><div className="specimen-top"><span>SPESIMEN 01</span><span className="outline-pill">BIJI BENIH</span></div><div className="hero-stage"><SeedIllustration/></div><div className="specimen-caption"><span className="specimen-number">01</span><div><h2>Dari benih kepada tunas.</h2><p>Apakah keadaan yang membolehkan<br/>perubahan ini berlaku?</p></div></div><div className="specimen-bottom"><span>PERHATIKAN. UJI. TEMUI.</span><span>→</span></div></aside></div>;
}

