import { useState } from 'react';
import { ArrowLeft, ArrowRight, UsersRound, UserRound } from 'lucide-react';
import { createSession, type Mode } from '../domain/model';
import { useLab } from '../state/LabContext';
export function Registration({ mode, onBack, onComplete }: { mode: Mode; onBack: () => void; onComplete: () => void }) {
  const { state, updateSession } = useLab(); const existing = state.session?.mode === mode ? state.session : null;
  const [name, setName] = useState(existing?.name ?? ''); const [className, setClassName] = useState(existing?.className ?? '');
  const [count, setCount] = useState(Math.min(existing?.members.length || 3,state.settings.maxMembers)); const [names, setNames] = useState<string[]>(existing?.members.map(m => m.name) ?? Array(5).fill(''));
  const [error, setError] = useState(''); const group = mode === 'group';
  function submit(e: React.FormEvent) { e.preventDefault(); if(state.settings.allowedModes!=='both'&&state.settings.allowedModes!==mode){setError('Mod ini telah dinyahaktifkan oleh guru. Kembali ke pilihan mod.');return;} if(group&&count>state.settings.maxMembers){setError('Bilangan ahli melebihi had guru. Pilih bilangan ahli semula.');return;} if (!name.trim() || !className.trim() || (group && names.slice(0, count).some(n => !n.trim()))) { setError('Lengkapkan nama, kelas dan nama setiap ahli sebelum meneruskan.'); return; }
    if (group && new Set(names.slice(0, count).map(n => n.trim().toLocaleLowerCase())).size !== count) { setError('Gunakan nama yang berbeza untuk mengenal pasti setiap ahli. Tambah nama keluarga jika perlu.'); return; }
    updateSession(createSession(mode, name, className, group ? names.slice(0, count) : [])); onComplete();
  }
  return <section className="panel registration"><button className="text-button" onClick={onBack}><ArrowLeft size={18}/> Pilihan mod</button><div className="eyebrow">LANGKAH 01 / KENALI PENYELIDIK</div><h1>{group ? 'Daftarkan kumpulan anda.' : 'Selamat datang, penyelidik.'}</h1><p className="muted">{group ? 'Kongsi satu tablet, jalankan eksperimen bersama.' : 'Masukkan maklumat anda untuk menyimpan kemajuan.'}</p><form onSubmit={submit} noValidate><div className="form-row"><label>{group ? 'Nama kumpulan' : 'Nama murid'}<input autoComplete="off" maxLength={70} value={name} onChange={e => setName(e.target.value)} placeholder={group ? 'Contoh: Kumpulan Tunas' : 'Nama penuh anda'} required/></label><label>Kelas<input maxLength={40} value={className} onChange={e => setClassName(e.target.value)} placeholder="Contoh: 1 Bestari" required/></label></div>{group && <><label className="count-label">Bilangan ahli<select value={count} onChange={e => setCount(Number(e.target.value))}>{Array.from({ length: state.settings.maxMembers - 1 }, (_, i) => i + 2).map(n => <option key={n} value={n}>{n} orang</option>)}</select></label><div className="members-fields">{Array.from({ length: count }, (_, i) => <label key={i}>Ahli {i + 1}<input maxLength={70} value={names[i] ?? ''} onChange={e => setNames(previous => { const next = [...previous]; next[i] = e.target.value; return next; })} placeholder={`Nama ahli ${i + 1}`} required/></label>)}</div><div className="info-strip"><UsersRound size={20}/><span>Peranan akan diberikan secara automatik. Semua ahli akan mengambil giliran.</span></div></>}{error && <p role="alert" className="error">{error}</p>}<div className="actions"><span className="small muted"><UserRound size={16}/> Tiada akaun diperlukan</span><button className="primary" type="submit">{group ? 'Tetapkan peranan' : 'Teruskan'} <ArrowRight size={18}/></button></div></form></section>;
}
