import { useState } from 'react';
import { Copy, Download, Printer } from 'lucide-react';
import baseStyles from '../styles.css?inline';
import reportStyles from '../learning.css?inline';
export const printableStyles = `body{margin:0;background:white;color:#173c38;font-family:Arial,sans-serif;padding:24px}.report-document{max-width:1000px;margin:auto}button{display:none} @page{size:A4;margin:14mm} @media print{body{padding:0}.report-section,.setup-summary article,.report-analysis li,.challenge-log article{break-inside:avoid}.report-table-wrapper{overflow:visible}.report-table{min-width:0!important;width:100%;font-size:10pt}.report-title h1{font-size:24pt}.identity-grid,.setup-summary{display:grid;grid-template-columns:1fr 1fr}.report-document{max-width:none}.score-breakdown{break-inside:avoid}}`;
export function reportHtml(documentElement:HTMLElement) {
  return `<!doctype html><html lang="ms"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Laporan Virtual Lab Sains Tingkatan 1</title><style>${baseStyles}\n${reportStyles}\n${printableStyles}</style></head><body>${documentElement.outerHTML}</body></html>`;
}
export function ReportActions({code,shareCode}:{code:string;shareCode?:string}) {
  const [message,setMessage]=useState(''),[manual,setManual]=useState(false),[manualValue,setManualValue]=useState('');
  const documentFor=(button:HTMLButtonElement)=>button.closest('.report-panel')?.querySelector<HTMLElement>('.report-document');
  async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setMessage(`${label} telah disalin.`);setManual(false);}catch{setManual(true);setManualValue(value);setMessage('Pilih kod di bawah dan salin secara manual.');}}
  return <div className="report-export"><div className="report-export-buttons"><button className="secondary" onClick={e=>{const doc=documentFor(e.currentTarget);if(!doc)return;const url=URL.createObjectURL(new Blob([reportHtml(doc)],{type:'text/html;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`laporan-${code.replace(/[^a-z0-9-]/gi,'')}.html`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Laporan HTML dimuat turun. Buka fail untuk membaca atau mencetak.');}}><Download size={18}/>Muat turun laporan</button>
  <button className="secondary" onClick={e=>{const doc=documentFor(e.currentTarget);if(!doc)return;const popup=window.open('','_blank');if(!popup){setMessage('Tetingkap cetak disekat. Muat turun laporan HTML dan cetak daripada fail tersebut.');return;}popup.opener=null;popup.document.write(reportHtml(doc));popup.document.close();popup.focus();popup.print();setMessage('Pilih “Simpan sebagai PDF” dalam dialog cetak jika tersedia.');}}><Printer size={18}/>Cetak / simpan PDF</button><button className="secondary" onClick={()=>copy(code,'Kod keputusan')}><Copy size={18}/>Salin kod keputusan</button>{shareCode&&<button className="secondary" onClick={()=>copy(shareCode,'Kod kelas')}><Copy size={18}/>Salin kod kelas</button>}</div><p className="small muted">Laporan HTML boleh dibuka tanpa internet. Kod ini ialah rujukan setempat bagi sesi ini.</p>{message&&<p role="status">{message}</p>}{manual&&<input aria-label="Kod untuk salinan manual" readOnly value={manualValue} onFocus={e=>e.target.select()}/>}</div>;
}
