import { Lightbulb, RotateCcw, X, Check } from 'lucide-react';
import type { TubeState } from '../domain/model';
import { currentHint, materialNames, recipes } from '../domain/experiment';
export function SetupInstructions({ tube, hintsEnabled, onRemove, onCheck, onHint, onClear, failed, onReview }: {
  tube: TubeState; hintsEnabled: boolean; onRemove: (material: TubeState['materials'][number]) => void; onCheck: () => void; onHint: () => void; onClear: () => void; failed: boolean; onReview: () => void;
}) {
  return <aside className="setup-instructions"><div className="eyebrow">PROTOKOL / TABUNG {tube.id}</div><h2>{recipes[tube.id].title}</h2><ol>{recipes[tube.id].instructions.map(text => <li key={text}>{text}</li>)}</ol><div className="contents-label">Kandungan tabung</div><div className="contents-list">{tube.materials.length ? tube.materials.map(material => <button key={material} onClick={() => onRemove(material)} aria-label={`Keluarkan ${materialNames[material]} dari Tabung ${tube.id}`}>{materialNames[material]}<X size={15}/></button>) : <p className="muted">Tabung masih kosong.</p>}</div><p className="small muted">Tap × untuk mengeluarkan bahan.</p><div className="setup-check-actions"><button className="primary" onClick={onCheck} disabled={tube.validated}>{tube.validated ? <><Check size={18}/> Penyediaan lengkap</> : `Semak Tabung ${tube.id}`}</button><button className="secondary" onClick={onClear} aria-label={`Kosongkan Tabung ${tube.id}`}><RotateCcw size={18}/></button></div>{failed && <div className="validation-feedback" role="status"><strong>Hmm… terdapat sesuatu yang kurang tepat.</strong><p>Bandingkan penyediaan anda dengan protokol.</p><button className="secondary" onClick={onReview}>Periksa semula</button></div>}{hintsEnabled && <button className="hint-button" onClick={onHint} disabled={tube.validated || (tube.hintLevel > 0 && tube.hintLevel < 3 && tube.attempts < tube.hintLevel)}><Lightbulb size={18}/>{tube.hintLevel >= 3 ? 'Lihat semula petunjuk' : `Dapatkan petunjuk (${tube.hintLevel}/3)`}</button>}{hintsEnabled && tube.hintLevel > 0 && tube.hintLevel < 3 && tube.attempts < tube.hintLevel && <p className="small muted">Cuba semak tabung sebelum petunjuk seterusnya.</p>}{currentHint(tube) && hintsEnabled && <div className="hint-text" role="status"><strong>Petunjuk {tube.hintLevel}</strong><p>{currentHint(tube)}</p></div>}</aside>;
}

